### PR TITLE
Update relude version bound to the v1.0

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Review by vrom911 — COMMENTED** [review]
Hey @TristanCacqueray !

Thanks a lot for your contribution 👍🏼 
Unfortunately, as `1.0` was a major release, there were breaking changes introduced, so Stan requires a few modifications in order to work with this version. Would you like to continue working on this?

**Comment by TristanCacqueray** [comment]
@vrom911 you are welcome :-)

Lets see if the last commit pass the CI.

**Comment by vrom911** [comment]
Yes, looks great! The only thing left is updating `stack.yaml` and we are good to go 👍🏼

**Review by chshersh — COMMENTED** [review]
Looks really nice 🙂 
One missing thing I noticed is upgrading the version Relude-specific HLint rules on CI (and fixing all new lints):

https://github.com/kowainik/stan/blob/9161ae83e1cffcc590552078956f7cce3aacf21f/.github/workflows/ci.yml#L113

**Review by vrom911 — APPROVED** [review]
Really nice! Thank you 🤗

**Comment by TristanCacqueray** [comment]
Sweet, you are welcome, thank you for relude and stan!

**Pull request merged**
